name: pull request ci

on:
  pull_request:
    branches: ['master']

defaults:
  run:
    shell: bash

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare actions
        uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Format check
        run: npm run format:check
      - name: Spell check
        run: npm run spell
      - name: Semantic version check
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        run: npm run svc
      - name: Tests
        run: npm run test
    timeout-minutes: 5
